# Site
name: "A Collection of Random Ideas"
title: "A Collection of Random Ideas"
description: ""
logo: 'assets/images/favicon.ico'
favicon: 'assets/images/favicon.ico'
url: rushichaudhari.github.io
baseurl: ''
google_analytics: ''
disqus: 'rushichaudhari'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  rushi:
    name: "Rushi"
    display_name: ""
    avatar: ''
    gravatar: 
    email: rushic24@gmail.com
    web: http://www.rushichaudhari.github.io/profile
    twitter: ''
    description: ""
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-233424324324324324"
adsense-data-ad-slot: "13423432438"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
