name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
  
    - name: Install python libs
      run: pip3 install requests python-frontmatter
    
    - name: Grant permission and Run
      env:
        DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
        SLEEP_TIME: ${{ secrets.SLEEP_TIME }}
        MARKDOWN_POSTS_PATH: ${{secrets.MARKDOWN_POSTS_PATH}}
      run: chmod +x ./.github/devpush.py && python3 ./.github/devpush.py
