name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    
    - name: Install python libs
      run: pip3 install requests python-frontmatter

    - name: execute py script # run the run.py to get the latest data
      run: |
        python ./.github/devpush.py
      env:
        DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
        SLEEP_TIME: ${{ secrets.SLEEP_TIME }}
        MARKDOWN_POSTS_PATH: ${{secrets.MARKDOWN_POSTS_PATH}}