name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
    - name: Publish articles on dev.to
      uses: "sinedied/publish-devto@30728bf375a0d24f91e18ae83ecdd219e5ac1878"
      with:
        files: 'content/posts/**/*.md'
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        github_token: ${{ secrets.GH_TOKEN }}
        conventional_commits: true
